# Model configuration
model:
  backbone: "resnet152"  # Backbone model for feature extraction
  pretrained: true
  num_classes: 11  # 10 digits + background

# Optimizer configuration
optimizer:
  name: "sgd"  # "sgd" or "adam"
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005

# Learning rate scheduler
scheduler:
  name: "step"
  step_size: 3
  gamma: 0.1

# Training configuration
training:
  num_epochs: 20
  batch_size: 4
  save_frequency: 1  # Save checkpoint every N epochs

# Testing configuration
testing:
  batch_size: 1
  confidence_threshold: 0.5  # Minimum confidence score for detections